---
--- Generated by Luanalysis
--- Created by LIU.
--- DateTime: 2026/1/24 21:41
---

local singleLimit = tonumber(ARGV[2])
local globalLimit = tonumber(ARGV[3])
local single = redis.call('hget', KEYS[1], ARGV[1])
-- 1. 检查是否超限
if single and tonumber(single) >= singleLimit then
    return 1
end
local global = redis.call('get', KEYS[2])
if global and tonumber(global) >= globalLimit then
    return 2
end
-- 2. 未超限。自增1
local s = redis.call('hincrby', KEYS[1], ARGV[1], 1)
local g = redis.call('incr', KEYS[2])
-- 3. 设置过期时间
if tonumber(s) == 1 then
    redis.call('expire', KEYS[1], 86400)
end
if tonumber(g) == 1 then
    redis.call('expire', KEYS[2], 86400)
end
return 0