---
--- Generated by Luanalysis
--- Created by LIU.
--- DateTime: 2026/1/21 21:27
---
-- KEYS[1] comment:action:{userId}         hash    k1  commentId  likeOrDislike  记录当前用户赞过或踩过某个评论
-- KEYS[2] comment:num:{commentId}         hash    k2  like       num           记录某个评论的总赞数
--                                                     dislike    num
-- KEYS[3] comment:dirty                   set     k3  commentId                记录赞或踩数量发生变化的评论id
-- ARGV[1] commentId
-- ARGV[2] action  like 或 dislike
local commentId = ARGV[1]
local newAction=ARGV[2]
local oldAction=redis.call('HGET',KEYS[1],commentId)
-- 1. 重复操作，取消
if oldAction==newAction then
    redis.call('HDEL',KEYS[1],commentId)
    redis.call('HINCRBY',KEYS[2],newAction,-1)
    redis.call('SADD',KEYS[3],commentId)
    return {'cancel',newAction}

--2. 新操作与旧操作不同，且旧操作不为nil。切换
elseif oldAction ~=false then
    redis.call('HINCRBY',KEYS[2],oldAction,-1)
    redis.call('HSET',KEYS[1],commentId,newAction)
    redis.call('HINCRBY',KEYS[2],newAction,1)
    redis.call('SADD',KEYS[3],commentId)
    return {'switch',oldAction,newAction}

--3. 新增  oldAction==nil
else
    redis.call('HSET',KEYS[1],commentId,newAction)
    redis.call('HINCRBY',KEYS[2],newAction,1)
    redis.call('SADD',KEYS[3],commentId)
    return { 'add', newAction }
end

